crypto: Rename kernel getpid to _afscrypto_getpid
When compiling the kernel extension on AIX 7.2+ using the
CLANG-based Open XL C 17.1.0+ compiler, the following
error is generated while building
src/external/heimdal/hcrypto/sha256.c:

    In file included from /home/build/openafs/src/external/heimdal/hcrypto/sha256.c:34:
    /home/build/openafs/src/crypto/hcrypto/kernel/config.h:91:21: error: static declaration of 'getpid' follows non-static declaration
    static_inline pid_t getpid(void) {return 1;};
                        ^
    ../h/proc.h:1344:15: note: previous declaration is here
    extern pid_t    getpid(void);
                    ^

Rename getpid() to _afscrypto_getpid(), like we do for calloc() and
various other functions, to ensure we don't conflict with any existing
getpid() declarations.

While we're changing this function anyway, fix the style in the function
and clarify some comments.

Change-Id: Ic7449c64fff9a7d8f5d98b2cf1c8830c255014c0
Reviewed-on: https://gerrit.openafs.org/16565
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Ben Huntsman <ben@huntsmans.net>
Tested-by: Ben Huntsman <ben@huntsmans.net>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>