afs: Use literal NULL for NULL function pointer
The clang compiler complains that this function pointer cast is not a
prototype.

   .../osi_file.c:141:27: error: this function declaration is not a
      prototype [-Werror,-Wstrict-prototypes]
    afile->proc = (int (*)())0;
                          ^
                           void

Just use NULL instead of trying to create a cast to 0.

Reviewed-on: https://gerrit.openafs.org/14902
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>
(cherry picked from commit 689fb56fca57274e73c8394e8588650449565cd8)

Change-Id: I61cf49178a80d011b0169a729c3a08e9829cddad
Reviewed-on: https://gerrit.openafs.org/15541
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Reviewed-by: Indira Sawant <indira.sawant@ibm.com>
Reviewed-by: Kailas Zadbuke <kailashsz@in.ibm.com>
Reviewed-by: Stephan Wiesand <stephan.wiesand@desy.de>