ptserver: Include ptprototypes.h in utils.c
utils.c implements many functions declared in ptprototypes.h; we should
include the header to make sure our definitions match the declared
prototypes.

Remove the prototype for NameHash() in ptprototypes.h, because the
function is only called in utils.c, and the current prototype doesn't
match the implementation, causing a compier error:

    /.../src/ptserver/utils.c:37:1: error: conflicting types for 'NameHash'; have 'afs_int32(char *)' {aka 'int(char *)'}
       37 | NameHash(char *aname)
          | ^~~~~~~~
    In file included from /.../src/ptserver/utils.c:21:
    /.../src/ptserver/ptprototypes.h:34:18: note: previous declaration of 'NameHash' with type 'afs_int32(unsigned char *)' {aka 'int(unsigned char *)'}
       34 | extern afs_int32 NameHash(unsigned char *aname);
          |                  ^~~~~~~~

It looks like NameHash() became out of sync with its prototype starting
in 79448c25ac (ptserver-prototypes-20090316). Also declare NameHash()
static, to ensure it doesn't have any callers outside of utils.c.

Change-Id: Ic926ae6fdf6d7fc30029bfb862f754a3736c05ec
Reviewed-on: https://gerrit.openafs.org/16947
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>