util: Add ktime test syms to liboafs_util.la.sym
Building with --disable-static results in several undefined references
to functions within the ktime.c and kreltime.c when linking the ktime-t
test code.
    /usr/bin/ld: .libs/ktime-t.o: in function `test_ktime_Str2int32':
    ktime-t.c:(.text+0x2e): undefined reference to `ktime_Str2int32'
    ...

The commits:
    'ktime: Add ktime unit tests' (e260c0b15f7e8)
    'ktime: Add kreltime unit tests' (bb846101e8908)

added tests for the functions provided by util/ktime, however the
dynamic library symbols for liboafs_util were not updated to include the
functions referenced by the new tests.

Ensure that liboafs_util.la.sym has all the public functions from
util/ktime.c and util/kreltime.c.

Resorted the entire file.

Change-Id: I275f248405a261049d632cdedc2c16a80deee9d2
Reviewed-on: https://gerrit.openafs.org/16445
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>