DARWIN: Cast arguments to afs_syscall_pioctl()
In recent versions of Xcode (around the release of macOS 14), mismatched
argument types are now flagged as errors instead of warnings:

    src/afs/afs_syscall.c:659:22: error: incompatible integer to pointer
                                  conversion passing 'afs_int32' (aka 'int') to
                                  parameter of type 'char *' [-Wint-conversion]

      afs_syscall_pioctl(uap->parm1, uap->parm2, uap->parm3,
                         ^~~~~~~~~~

    src/afs/afs_syscall.c:659:46: error: incompatible integer to pointer
                                  conversion passing 'afs_int32' (aka 'int') to
                                  parameter of type 'caddr_t' (aka 'char *')
                                  [-Wint-conversion]

      afs_syscall_pioctl(uap->parm1, uap->parm2, uap->parm3,
                                                 ^~~~~~~~~~

Add approriate casts to parameters 1 and 3.

[mvitale: commit message details]

Change-Id: I7585c3c216d97bef821d5410edd2f99456ad6550
Reviewed-on: https://gerrit.openafs.org/16141
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Tested-by: Andrew Deason <adeason@sinenomine.net>