doc: Remove stray sect2 end tag
Commit 2f435309c75dfd8ffe0cfb3e1a54749437cba3be (Remove NoAuth
procedures from Admin Guide) introduced a syntax error in the Admin
Reference guide xml source.

The </sect2> end tag which matched the <sect2 id="Header_427"> start tag
should have been removed in the last hunk of that commit.

This change removes the stray end tag to fix the xsltproc error:

    Build the book set list...
    openafs/doc/xml/AdminGuide/auagd014.xml:1119: parser error : Opening and ending tag mismatch: sect1 line 1037 and sect2
        </sect2>
                ^
    ...
    Error: xsltproc failed
    make: *** [Makefile:42: auagd000.pdf] Error 1

Change-Id: I91b9b5335c2ddd6ab60d3bc061703c8396003a43
Reviewed-on: https://gerrit.openafs.org/15120
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>