AIX: Redefine free_sock_hash_table for clang
On AIX, when using the CLANG-based Open XL C 17.1.0+ compiler, during
the kernel extension build, we include the system header
sys/socketvar.h. Without the fix for APAR IJ50768, this file contains
the following statement:

extern struct free_sock_hash_bucket free_sock_hash_table[];

This statement causes the following compiler error when building
src/external/heimdal/hcrypto/sha256.c (and others):

In file included from /home/build/openafs/src/external/heimdal/hcrypto/sha256.c:34:
In file included from /home/build/openafs/src/crypto/hcrypto/kernel/config.h:30:
In file included from /home/build/openafs/src/afs/sysincludes.h:276:
../sys/socketvar.h:158:57: error: array has incomplete element type 'struct free_sock_hash_bucket'
extern struct free_sock_hash_bucket free_sock_hash_table[];
                                                        ^
../sys/socketvar.h:158:15: note: forward declaration of 'struct free_sock_hash_bucket'
extern struct free_sock_hash_bucket free_sock_hash_table[];
              ^

This issue is tracked by IBM in APAR IJ50768, et al:

https://www.ibm.com/support/pages/apar/IJ50768

As this is an IBM-supplied header, we cannot change it.  Since we don't
actually need free_sock_hash_table, redefine it to something that will
compile, so we can build on AIX without the fix for IJ50768.

Unfortuntely, sys/socketvar.h is included in a number of different
places, several of which don't have many earlier includes in common, and
the redefinition is needed before sys/socketvar.h is included. So,
perform this workaround in param.rs_aix72.h and param.rs_aix73.h, which
are included very early by all files.

Change-Id: Ia60f59bb724f2d66e315db374f790c473886320d
Reviewed-on: https://gerrit.openafs.org/16089
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>