kauth: Add LIB_crypt to LT_libs
Since OpenAFS 1.0, kauth's Andrew_StringToKey() has contained a
reference to crypt(). This is provided by $(LIB_crypt) (usually
-lcrypt), but not all everything that links against liboafs_kauth.la
also links to LIB_crypt. This causes the build to fail with
--disable-static:

    $ make V=0
      LD  .../src/tbutc/butc
    /usr/bin/ld: ../../src/kauth/.libs/liboafs_kauth.so: undefined reference to `crypt'
    collect2: error: ld returned 1 exit status

    FAILED COMMAND: /bin/bash ../../libtool --quiet --mode=link --tag=CC gcc [...] -o butc [...] ../../src/kauth/liboafs_kauth.la [...] -lafshcrypto -lrokenafs -lpthread -lresolv

To fix this, link against LIB_crypt when building liboafs_kauth.la, so
anything linking against liboafs_kauth.la should also link against
LIB_crypt.

Change-Id: I9f46f3c429848b1ae67c8bf28a7698df0c084892
Reviewed-on: https://gerrit.openafs.org/15992
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>