clang-16: Fix simple unused-but-set variables
Clang-16 is flagging variables as unused-but-set-variables resulting in
build errors when --enable-warning is used.

   db_verify.c:996:9: error: variable 'builtinUsers' set but not used
      [-Werror,-Wunused-but-set-variable]
       int builtinUsers = 0;
           ^
Remove the variables that are set but never actually used.

This commit fixes the simpler cases where variables are only set but
not used elsewhere.

Reviewed-on: https://gerrit.openafs.org/15178
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>
(cherry picked from commit afafde158ff875d2459bb81ac373cde3e45dac03)

Change-Id: I65cd27325b768ba192831401f4ac71e94071ecc7
Reviewed-on: https://gerrit.openafs.org/15273
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Harish Sharma <Harish.Sharma1@ibm.com>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Stephan Wiesand <stephan.wiesand@desy.de>