AIX: Pass cred to afs_fid()
Currently, osi_vnodeops.c fails to build on AIX when using Open XL C
17.1+ on AIX 7.2+:

    /home/build/openafs/src/afs/AIX/osi_vnodeops.c:226:29: error: too few arguments to function call, expected 3, have 2
        error = afs_fid(vp, fidp);
                ~~~~~~~         ^
    /home/build/openafs/src/afs/afs_prototypes.h:1186:5: note: 'afs_fid' declared here
    int afs_fid(OSI_VC_DECL(avc), struct fid *fidpp, struct ucred *credp);
        ^

This appears to have been broken since OpenAFS 1.0, but has not caused a
build error until we used Open XL C 17.1+.

To fix this, pass the ucred we're given in afs_fid() to afs_gn_fid().

Change-Id: I78cdb733def9ee0bacdf9650a77b5f970bb5509a
Reviewed-on: https://gerrit.openafs.org/16570
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Reviewed-by: Ben Huntsman <ben@huntsmans.net>
Tested-by: Ben Huntsman <ben@huntsmans.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>