hcrypto: rename abort to _afscrypto_abort
The Linux 6.5 commit:
    panic: make function declarations visible (d9cdb43189)
added a declaration for abort into panic.h.

When building the Linux kernel module, the build fails with the
following:

  src/crypto/hcrypto/kernel/config.h:95:20: error: static declaration of
      ‘abort’ follows non-static declaration
    95 | static_inline void abort(void) {osi_Panic("hckernel aborting\n"
         );}
       |                    ^~~~~
    ...
                 from ./include/linux/wait.h:9,
                 from /openafs/src/afs/sysincludes.h:118,
                 from /openafs/src/crypto/hcrypto/kernel/config.h:30:
    ./include/linux/panic.h:36:6: note: previous declaration of ‘abort’
         with type ‘void(void)’
    36 | void abort(void);
       |      ^~~~~

Update the declaration in hcrypto/kernel/config.h to change the function
name from abort to _afscrypto_abort and use a preprocessor define to
map abort to _afscrypto_abort.

Reviewed-on: https://gerrit.openafs.org/15501
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>
Tested-by: Benjamin Kaduk <kaduk@mit.edu>
(cherry picked from commit c4c16890d9d2829f6bef1ef58feafb30b1d59da3)

Change-Id: I54cc9156b98320d04fe6f7bb595a150d5ba87b49
Reviewed-on: https://gerrit.openafs.org/15523
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Stephan Wiesand <stephan.wiesand@desy.de>