crypto: Prefix kernel gettimeofday with _afscrypto
When compiling the kernel extension on AIX 7.2+ using the CLANG-based
Open XL C 17.1.0+ compiler, the following error is generated while
building src/external/heimdal/hcrypto/sha256.c:

    In file included from /home/build/openafs/src/external/heimdal/hcrypto/sha256.c:34:
    /home/build/openafs/src/crypto/hcrypto/kernel/config.h:118:19: error: static declaration of 'gettimeofday' follows non-static declaration
    static_inline int gettimeofday(struct timeval *tp, void *tzp)
                      ^
    ../h/time.h:248:12: note: previous declaration is here
    extern int gettimeofday(struct timeval *__restrict__, void *__restrict__);
               ^

Rename gettimeofday() to _afscrypto_gettimeofday(), like we do for
calloc() and various other functions, to ensure we don't conflict with
any existing gettimeofday() declarations.

Change-Id: Iadb9197372c9bea235c977cc2b61600b9e0c57b1
Reviewed-on: https://gerrit.openafs.org/16566
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Ben Huntsman <ben@huntsmans.net>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Tested-by: Ben Huntsman <ben@huntsmans.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>