afsd: Properly declare aix_vmount and vmountdata
The AIX-specific functions aix_vmount() and vmountdata() are missing
return types, and vmountdata is referenced before we declare it. These
cause errors when using the clang-based xlc 17.1:

    .../src/afsd/afsd_kernel.c:386:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
    aix_vmount(const char *cacheMountDir)
    ^
    int
    .../src/afsd/afsd_kernel.c:407:5: error: call to undeclared function 'vmountdata'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        vmountdata(vmountp, "AFS", cacheMountDir, "", "", "", "rw");
        ^
    .../src/afsd/afsd_kernel.c:415:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
    vmountdata(struct vmount * vmtp, char *obj, char *stub, char *host,
    ^

Declare these 'static' and with proper return types, and move
aix_vmount() so it's after vmountdata().

Change-Id: Ie31dddaae515c914087a34efacfe3427eda22d0b
Reviewed-on: https://gerrit.openafs.org/15433
Reviewed-by: Ben Huntsman <ben@huntsmans.net>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>