kauth: Do not redefine vfprintf
kaserver.c redefines vfprintf in terms of the historical _doprnt
function, presumably to work around quirks of old platforms. This
should not be necessary anymore, since we call vfprintf() normally in
various other places throughout the tree without trouble.

Using _doprnt causes problems on various platforms (as can be seen by
the long #ifdef before it), including now AIX when using the
clang-based xlc 17.1:

        .../src/kauth/kaserver.c:99:5: error: call to undeclared function '_doprnt'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            vfprintf(stderr, fmt, pvar);
            ^
        .../src/kauth/kaserver.c:60:35: note: expanded from macro 'vfprintf'
        #define vfprintf(stream,fmt,args) _doprnt(fmt,args,stream)
                                          ^

Instead of adding more conditions to the #ifdef, just get rid of this
weird workaround altogether.

Change-Id: Ie4e965229ed8e8636c6e6405cc33a4937e2ccabc
Reviewed-on: https://gerrit.openafs.org/15431
Reviewed-by: Ben Huntsman <ben@huntsmans.net>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>