DARWIN: Eliminate "incompatible function pointer" build error
When building OpenAFS under macos 27 beta (Golden Gate) with
Xcode 27 beta 5, the following build error occurs:

/Users/devlab/src/openafs/src/afs/DARWIN/osi_file.c:202:17: error:
	incompatible function pointer types assigning to
      'int (*)(struct osi_file *, afs_int32)' (aka 'int (*)(struct osi_file *, int)')
	from
      'int (*)(void)' [-Wincompatible-function-pointer-types]

  202 |     afile->proc = (int (*)())0;
      |                 ^ ~~~~~~~~~~~~

Change the assignment to a simple NULL.

Reviewed-on: https://gerrit.openafs.org/16948
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
(cherry picked from commit 2f8b7da15ff15d7def18af4feff7950ecab3e9cc)

Change-Id: I42ffc679acff8ec4bad25efdfb6b7629ba49a617
Reviewed-on: https://gerrit.openafs.org/16954
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Ganesh G. Chaudhari <gangovind@in.ibm.com>
Tested-by: Ganesh G. Chaudhari <gangovind@in.ibm.com>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>
Reviewed-by: Kailas Zadbuke <kailashsz@in.ibm.com>