macos: Remove SDKROOT from AklogAuthPlugin project
An attempt to build AklogAuthPlugin with the default SDK fails:

  xcodebuild --project AklogAuthPlugin.xcodeproj

  error: unable to find sdk 'macosx10.6' (in target 'AklogAuthPlugin'
         from project 'AklogAuthPlugin')
  warning: There are no architectures to compile for because the
         VALID_ARCHS build setting is an empty list. (in target
         'AklogAuthPlugin' from project 'AklogAuthPlugin')
  ** BUILD FAILED **

Remove the SDKROOT=macosx10.6 specification from the project file.

Reviewed-on: https://gerrit.openafs.org/16151
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
(cherry picked from commit 2e149f1c9dbac198e646d63cec54dd2ca83c4e8d)

Change-Id: I173056eee67c8e00c4b87420ebf2daea76ba6b42
Reviewed-on: https://gerrit.openafs.org/16186
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>