rx: Add rx_Writev* to liboafs_rx.la.sym
Since OpenAFS 1.0, the fileserver has contained references to
rx_WritevAlloc and rx_WritevProc (via rx_Writev()), but our
liboafs_rx.la.sym has never exported these. This causes the fileserver
to fail to build with --disable-static:

    $ make V=0
    [...]
      LD  .../src/viced/fileserver
    /usr/bin/ld: afsfileprocs.o: in function `FetchData_RXStyle':
    .../src/viced/afsfileprocs.c:6345: undefined reference to `rx_WritevAlloc'
    /usr/bin/ld: .../src/viced/afsfileprocs.c:6359: undefined reference to `rx_WritevProc'
    collect2: error: ld returned 1 exit status

    FAILED COMMAND: /bin/bash ../../libtool --quiet --mode=link --tag=CC gcc [...] -o fileserver [...]

Add the missing symbols to liboafs_rx.la.sym.

Change-Id: I88b73ed4b639e9c128c8d3c80bc60fc99e6aa3e1
Reviewed-on: https://gerrit.openafs.org/15991
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Tested-by: Andrew Deason <adeason@sinenomine.net>