libadmin: Fix RPCStatsStateGet 'rpc' prototype
clang-16 is flagging a incompatible-function-pointer-types warning which
results in build errors when --enable-warning is turned on.

   client.c:498:13: error: incompatible function pointer types passing
      'int (struct rx_connection *, afs_int32 *)'
      (aka 'int (struct rx_connection *, int *)') to parameter of type
      'int (*)(struct rx_connection *, afs_RPCStatsState_p)'
      (aka 'int (*)(struct rx_connection *, afs_RPCStatsState_t *)')
      [-Wincompatible-function-pointer-types]

    (conn, RXSTATS_QueryPeerRPCStats, &state, &st)) {
           ^~~~~~~~~~~~~~~~~~~~~~~~~

Update the 'util_RPCStatsStateGet()' function's parameter to match the
function type for the RPC functions actually being called.

Change-Id: I4354dff2733ce2319b27a2f047cfe4a21ef3bcc8
Reviewed-on: https://gerrit.openafs.org/15180
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>