DARWIN: ANSIfy functions
Convert the remaining K&R style function declarations to ANSI in the
DARWIN source and and clean up nearby whitespace errors.

[1.8: This fixes build errors on macOS 27 Golden Gate and Xcode
  beta 5, such as:
  /Users/devlab/src/openafs/src/afs/DARWIN/osi_inode.c:31:10: error: unknown type name 'fs'
   31 | getinode(fs, dev, inode, vpp, perror)
      |          ^
  /Users/devlab/src/openafs/src/afs/DARWIN/osi_inode.c:31:14: error: unknown type name 'dev'
   31 | getinode(fs, dev, inode, vpp, perror)
      |              ^
  /Users/devlab/src/openafs/src/afs/DARWIN/osi_inode.c:31:19: error: unknown type name 'inode'
   31 | getinode(fs, dev, inode, vpp, perror)
      |                   ^
  /Users/devlab/src/openafs/src/afs/DARWIN/osi_inode.c:31:26: error: unknown type name 'vpp'
   31 | getinode(fs, dev, inode, vpp, perror)
      |                          ^
  /Users/devlab/src/openafs/src/afs/DARWIN/osi_inode.c:31:31: error: unknown type name 'perror'
   31 | getinode(fs, dev, inode, vpp, perror)
      |                               ^
  /Users/devlab/src/openafs/src/afs/DARWIN/osi_inode.c:31:38: error: expected ';' after top level declarator
   31 | getinode(fs, dev, inode, vpp, perror)
      |                                      ^
      |                                      ;
]

Reviewed-on: https://gerrit.openafs.org/16152
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
(cherry picked from commit 2da2d6d09556585246c6190ac6365ebd0386174c)

Change-Id: Iaf748be665553c03daf984aa195a67e656c2fd9a
Reviewed-on: https://gerrit.openafs.org/16955
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Ganesh G. Chaudhari <gangovind@in.ibm.com>
Tested-by: Ganesh G. Chaudhari <gangovind@in.ibm.com>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>
Reviewed-by: Kailas Zadbuke <kailashsz@in.ibm.com>