aklog: Put ${AKLIBS} after ${AFSLIBS} on the linker command line
Systems with newer, stricter linkers (such as Ubuntu saucy) require
this ordering because libauth.a uses symbols from libk5crypto.

Fixes this build failure:
gcc -o aklog -g -O -I/…/openafs/src/config -I/…/openafs/include -I. -I.  -D_LARGEFILE64_SOURCE  -DALLOW_REGISTER   aklog.o aklog_roken.o krb_util.o linked_list.o   -Wl,-Bsymbolic-functions -Wl,-z,relro -lkrb5 -lk5crypto -lcom_err /…/openafs/lib/libprot.a /…/openafs/lib/libauth.a /…/openafs/lib/libubik.a /…/openafs/lib/librxkad.a /…/openafs/lib/libsys.a /…/openafs/lib/librx.a /…/openafs/lib/libsys.a /…/openafs/lib/liblwp.a /…/openafs/lib/libdes.a /…/openafs/lib/libafscom_err.a /…/openafs/lib/libcmd.a /…/openafs/lib/libafsutil.a -lresolv
/usr/bin/ld.bfd.real: /…/openafs/lib/libauth.a(akimpersonate.o): undefined reference to symbol 'krb5_c_make_random_key@k5crypto_3_MIT'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libk5crypto.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[5]: *** [aklog] Error 1
make[5]: Leaving directory `/…/openafs/src/aklog'

Change-Id: Ibb12178d85e37e21320706eaafb84c7457d16e6c
Signed-off-by: Anders Kaseorg <andersk@mit.edu>
Reviewed-on: http://gerrit.openafs.org/10107
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Christof Hanke <christof.hanke@rzg.mpg.de>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>
Reviewed-by: Derrick Brashear <shadow@your-file-system.com>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Stephan Wiesand <stephan.wiesand@desy.de>