AIX: Declare osi_Panic with unspecified args
When compiling the kernel extension on AIX 7.2+ using the CLANG-based
Open XL C 17.1+, calls to osi_Panic generate the following compiler
error:

    In file included from /home/build/openafs/src/external/heimdal/hcrypto/sha256.c:34:
    /home/build/openafs/src/crypto/hcrypto/kernel/config.h:101:75: error: too few arguments to function call, expected 4, have 1
    static_inline void _afscrypto_abort(void) {osi_Panic("hckernel aborting\n");}
                                               ~~~~~~~~~                      ^
    /home/build/openafs/src/rx/rx_kernel.h:50:13: note: 'osi_Panic' declared here
    extern void osi_Panic(char *fmt, void *a1, void *a2, void *a3);
                ^

These calls are indeed broken, of course, but the older AIX compilers
allowed these calls (XL C 16.1 and earlier). To make the clang-based
compilers allow these calls, but still use the same non-varargs
implementation of osi_Panic(), just declare osi_Panic with unspecified
args. This is similar to how things worked before prototypes were added
for osi_Panic() way back before commits 8aa9d07e35 (rx-varargs-20080924)
and b147521611 (aix-prototype-fixes-20081215).

Change-Id: I292b2f3b275eef52502000c6b214b2bcb2ee459d
Reviewed-on: https://gerrit.openafs.org/16567
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Ben Huntsman <ben@huntsmans.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>