fsint: Add RXAFS_GetXStats to liboafs_fsint.la.sym
Since OpenAFS 1.0, xstat_fs_test and xstat_cm_test have contained
references to RXAFS_GetXStats and RXAFCB_GetXStats, respectively, but
these are not exported by our liboafs_fsint.la.sym. This causes the
build to fail with --disable-static:

    $ make V=0
      LD  .../src/xstat/xstat_cm_test
    /usr/bin/ld: ./.libs/liboafs_xstat_cm.so: undefined reference to `RXAFSCB_GetXStats'
    collect2: error: ld returned 1 exit status

    FAILED COMMAND: /bin/bash ../../libtool --quiet --mode=link --tag=CC gcc [...] -o xstat_cm_test xstat_cm_test.o liboafs_xstat_cm.la [...]
[...]
      LD  .../src/xstat/xstat_fs_test
    /usr/bin/ld: ./.libs/liboafs_xstat_fs.so: undefined reference to `RXAFS_GetXStats'
    collect2: error: ld returned 1 exit status

    FAILED COMMAND: /bin/bash ../../libtool --quiet --mode=link --tag=CC gcc [...] -o xstat_fs_test xstat_fs_test.o liboafs_xstat_fs.la [...]

Add the missing functions to liboafs_fsint.la.sym.

Change-Id: If58262eb017fd12819f59edda1e99dd9a6e8042b
Reviewed-on: https://gerrit.openafs.org/15993
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>