clang: Don't redefine printf in salvage.c
The Gentoo distribution changed the default fortify_source setting for
clang (to match the default being used for gcc).  This change causes the
following build error:

    src/dir/salvage.c:26:9: error: 'printf' macro redefined
        [-Werror,-Wmacro-redefined]
            ^
    /usr/include/bits/stdio2.h:89:11: note: previous definition is here
          ^
    1 error generated.

If the fortify_source level is greater than 1, glibc can define printf
as a macro.  The clang compiler has a default check for macro
redefinitions (-Wmacro-redefined), while gcc does not provide this
option.

Remove the:
   #define printf Log
in src/dir/salvage.c and update callers to use Log() instead of
printf().

Clean up lines that split the call to Log and its first parameter.  Fix
the indentation for Log's parameters.

There are no functional changes with this commit.

Reviewed-on: https://gerrit.openafs.org/15462
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>
(cherry picked from commit df7f841f3852b5417a1d4ebc981780f2d7651b60)

Change-Id: I9a7d9e70184eb1dbd04f2b1a0e9a668138baaabe
Reviewed-on: https://gerrit.openafs.org/15548
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Indira Sawant <indira.sawant@ibm.com>
Reviewed-by: Kailas Zadbuke <kailashsz@in.ibm.com>
Reviewed-by: Stephan Wiesand <stephan.wiesand@desy.de>