libuafs: include com_err.h in ukernel_swig.i
clang-16 is flagging an implicit-function-definition which results in a
build error when --enable-warning is turned on.

    PERLUAFS/ukernel_swig_perl.c:1585:9: error: call to undeclared
        function 'afs_com_err'; ISO C99 and later do not support
        implicit function declarations [-Wimplicit-function-declaration]
      afs_com_err("AFS::ukernel", code, "parsing line: '%s'", line);
      ^

Add an include for afs/com_err.h to resolve the warning.

Reviewed-on: https://gerrit.openafs.org/15179
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>
(cherry picked from commit 4be3e5d31fa3fbe6c80ad0973430074124b157bc)

Change-Id: I62785fe6248cb4b26f680c2db044f59511a1e02e
Reviewed-on: https://gerrit.openafs.org/15268
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Harish Sharma <Harish.Sharma1@ibm.com>
Reviewed-by: Stephan Wiesand <stephan.wiesand@desy.de>