UKERNEL: Remove most usr_* threading abstractions
UKERNEL defines a set of usr_* abstractions for threading and locking
primitives (for example: usr_mutex_t, usr_cond_signal(), etc). Most of
these aren't very useful and just make UKERNEL code harder to read: most
map one-to-one to opr or pthread primitives, which are the only
threading primitives we can use.

Get rid of this extra layer of abstraction, and change most of these to
use the corresponding opr or pthread type/call directly. A few macros
are kept for now, since there are currently no opr primitives for, say,
spawning a thread.

Include afs/opr.h in opr/lock.h, to make sure the opr lock abstractions
can use opr_Assert/opr_Verify. Without this, the new opr locking
references in this commit cause build failures, such as:

/bin/sh ../../libtool --quiet --mode=compile --tag=CC  gcc [...] -DKERNEL -DUKERNEL [...] -DAFS_PTHREAD_ENV  -o keys.lo -c [...]/keys.c
In file included from /.../src/rx/UKERNEL/rx_kmutex.h:19,
                 from ../rx/rx.h:14,
                 from /.../src/auth/keys.c:33:
/.../include/opr/lock.h: In function ‘opr_cv_timedwait’:
/.../include/opr/lock.h:87:5: error: implicit declaration of function ‘opr_Assert’ [-Werror=implicit-function-declaration]
     opr_Assert(code == 0 || code == ETIMEDOUT);

Change-Id: I45c5bfcbfe751c045d944b92b08ce475d1b1612b
Reviewed-on: https://gerrit.openafs.org/16490
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>