dumpscan: Include time.h
Various parts of dumpscan use ctime(), time(), etc, but don't include
time.h. This causes errors on AIX when using the clang-based xlc 17.1,
such as:

    .../src/tools/dumpscan/parsevol.c:286:35: error: call to undeclared function 'ctime'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                printf("%s%s", field->label, ctime(&when));
                                             ^

Include time.h in these files, so we have declarations for these
functions.

Change-Id: I0247a55952640585ff3b27d2b0e47e09dea531a0
Reviewed-on: https://gerrit.openafs.org/15435
Reviewed-by: Ben Huntsman <ben@huntsmans.net>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>