Linux: implement aops->migrate_folio
When the address_space_operations method writepages() was implemented in
the openafs commit:
 'linux: convert aops->writepage to writepages' (b2c039541d66e)
there should have been an implementation for the
aops->migrate_folio method added as well (though it isn't mandatory).

Linux provides a fallback if the filesystem has not implemented the
migrate_folio method, however the fallback will issue a WARN_ONCE()
kernel message:

[ 1692.812667] afs_file_aops [libafs] does not implement migrate_folio
[ 1692.812745] WARNING: CPU: 1 PID: 62 at mm/migrate.c:1053 move_to_new_folio+0x1a8/0x260
[ 1692.812768] Modules linked in: libafs(PO)
 ... followed by registers and a stack trace ...

Since openafs doesn't use folio->private, the Linux provided function
migrate_folio() can be used.

Move the preprocessor check that defines LINUX_WRITEPAGES_USES_FOLIOS
towards the top of the file and add an include for linux/migrate.h.

Initialize aops->migrate_folio element in the afs_file_aops structure
to use migrate_folio().

Note: the migrate_folio method is not documented as being mandatory for
a filesystem to implement, however as noted above a kernel warning is
issued if a filesystem doesn't implement the method.

Looking a several of the other Linux filesystems, the commit messages
associated with converting writepage -> writepages do mention having
to add a aops->migrate_folio call.  See the Linux commits:
  'ceph: Remove ceph_writepage()' (19a2881104354) and
  'orangefs: Remove orangefs_writepage()' (506382dbbedc0)

Most in-tree Linux filesystems use filemap_migrate_folio(), which we
cannot use because it is GPL-only. migrate_folio() is almost identical
to filemap_migrate_folio(); the only differences that are
filemap_migrate_folio() handles the folio's folio->private (which we do
not use), and migrate_folio() BUG()s if the folio's "writeback" flag is
set (which should not happen; Linux waits for writeback to finish before
migrating pages).

Reviewed-on: https://gerrit.openafs.org/16689
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
(cherry picked from commit daa3eef78addb187ced13355bff01a83f8d16f01)

Change-Id: I53108b95e8eb695d951425e7b2d20e0b244736e7
Reviewed-on: https://gerrit.openafs.org/16709
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>