FBSD: Build support for FreeBSD 13
Add sysnames and param.h files for FreeBSD 13.0 and 13.1.

Note that our param.h does differ from the FreeBSD 12 param.h, in that
AFS_64BITUSERPOINTER_ENV is defined for both UKERNEL and non-UKERNEL.
Otherwise, afs_pointer_to_int() causes warnings when building UKERNEL
(due to newer clang):

    .../src/afs/afs_icl.c:680:39: error: cast to smaller integer type 'afs_uint32' (aka 'unsigned int') from 'pthread_t' (aka 'struct pthread *') [-Werror,-Wpointer-to-int-cast]
        ICL_APPENDINT32(logp, (afs_int32) osi_ThreadUnique());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
    .../src/afs/afs_osi.h:201:28: note: expanded from macro 'osi_ThreadUnique'
                                    ^
    .../src/afs/UKERNEL/sysincludes.h:230:30: note: expanded from macro 'osi_getpid'
                                    ^
    .../include/afs/stds.h:282:37: note: expanded from macro 'afs_pointer_to_int'
                                        ^
    .../src/afs/afs_icl.c:523:41: note: expanded from macro 'ICL_APPENDINT32'
            (lp)->datap[(lp)->firstFree] = (x); \
                                            ^

Change-Id: I525c2df5981427d3ad1105030331c06fb7a59d78
Reviewed-on: https://gerrit.openafs.org/15160
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>