opr: Add explicit 32-bit casts in opr_time.h
WINNT Visual Studio 2005 complains about a couple of our conversions
from 64-bit 'ticks' to a 32-bit value:

        cl [...] /c c_ident.cpp
    cl : Command line warning D9025 : overriding '/W4' with '/W3'
    c_ident.cpp
    C:\BuildBot\gerrit-dev-windows-vs2005-amd64-checked\build\dest\amd64_w2k\free\include\opr/time.h(347) : error C2220: warning treated as error - no 'object' file generated
    C:\BuildBot\gerrit-dev-windows-vs2005-amd64-checked\build\dest\amd64_w2k\free\include\opr/time.h(347) : warning C4244: '=' : conversion from 'const afs_int64' to 'afs_uint32', possible loss of data
    C:\BuildBot\gerrit-dev-windows-vs2005-amd64-checked\build\dest\amd64_w2k\free\include\opr/time.h(365) : warning C4244: 'return' : conversion from 'afs_int64' to 'afs_int32', possible loss of data
    NMAKE : fatal error U1077: 'C:\progra~2\MICROS~2\VC\bin\amd64\cl.EXE' : return code '0x2'

The results of these calculation cannot actually be outside the range of
a 32-bit integer (they are mod X, where X is a 32-bit value), so just
add explicit casts to silence the warnings.

This error was introduced in commit 4719dc7a1b
(Introduce ViceLog_limit(), afs_warn_limit()), because it added an
include for opr/time.h in afsutil.h.

Change-Id: I05bfcbdf28c4d396cc2a1942ade00daa0b075927
Reviewed-on: https://gerrit.openafs.org/16949
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Tested-by: Andrew Deason <adeason@sinenomine.net>