AIX: Rename afs_badop() to afs_aix_badop()
When compiling the kernel extension on AIX 7.2+ using the CLANG-based Open XL C
17.1+ compiler, osi_vfsops.c fails to build:

    /home/build/openafs/src/afs/AIX/osi_vfsops.c:235:1: error: static declaration of 'afs_badop' follows non-static declaration
    afs_badop()
    ^
    /home/build/openafs/src/afs/afs_prototypes.h:987:12: note: previous declaration is here
    extern int afs_badop(void);
               ^

This is because we declare a cross-platform afs_badop() in
afs_prototypes.h (implemented in afs_util.c), and also an AIX-specific
afs_badop() in osi_vfsops.c.

To fix this, rename the AIX-specific afs_badop() to be afs_aix_badop().

Change-Id: I9eb2a4ab025c547c99db627b184e8f7d4c3e7e63
Reviewed-on: https://gerrit.openafs.org/16569
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Reviewed-by: Ben Huntsman <ben@huntsmans.net>
Tested-by: Ben Huntsman <ben@huntsmans.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>