rxgk: Initialize 'iterations'
gcc 4.4.7 (used on RHEL6) throws a warning that 'iterations' is used
uninitialized:

    .../src/rxgk/rxgk_crypto_rfc3961.c: In function 'PRFplus':
    .../src/rxgk/rxgk_crypto_rfc3961.c:621: error: 'iterations' may be used uninitialized in this function [-Wuninitialized]

It's not actually possible for 'iterations' to be used uninitialized;
we only use it in the 'done' destructor if 'pre_key' is set. But
initialize 'iterations' to 0 to avoid the warning.

Change-Id: I7ec3d033847a8804899f4d9fe163a56586812d4d
Reviewed-on: https://gerrit.openafs.org/15750
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>