UKERNEL: Set _FILE_OFFSET_BITS earlier
Since commit 47ac8ba702 (libuafs-set-fileoffsetbits-20090112), we have
always set _FILE_OFFSET_BITS to 64 when UKERNEL is defined, so our
UKERNEL interfaces are compatible with FUSE. However, this is done after
we potentially include sys/types.h, which includes various other headers
that look at _FILE_OFFSET_BITS to determine the size of off_t and other
similar types. By the time we define _FILE_OFFSET_BITS, it's too late,
and the size for off_t et al have already been determined.

When building against fuse3, this causes a build problem on 32-bit x86,
because fuse3 has a static assert to make sure that off_t is 64 bits:

    In file included from /usr/include/fuse3/fuse.h:19,
                     from ./afsd_fuse.c:53:
    /usr/include/fuse3/fuse_common.h:1155:1: error: static assertion failed: "fuse: off_t must be 64bit"
     1155 | _Static_assert(sizeof(off_t) == 8, "fuse: off_t must be 64bit");
          | ^~~~~~~~~~~~~~
    make[4]: *** [Makefile:61: afsd_fuse.o] Error 1

To avoid this, just move our define for _FILE_OFFSET_BITS earlier,
before including anything.

Note that this did not happen for fuse2, because 'pkg-config --cflags'
for fuse2 includes -D_FILE_OFFSET_BITS=64, so the define was included in
the CFLAGS when we built afsd_fuse.c.

Change-Id: Ia69f53676e51449c34b856894fa53c3ba920476c
Reviewed-on: https://gerrit.openafs.org/16919
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Reviewed-by: Gaurav Saxena <gsaxena@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>