vol: add missing include of stdint.h to volinodes.h
volinodes.h requires stdint.h for use of uintptr_t:

In file included from vutil.c:55:0:
volinodes.h: In function 'init_inode_info':
volinodes.h:109:45: error: 'uintptr_t' undeclared (first use in this function); did you mean 'intptr_t'?
  stuff[i].inode = (Inode*)((char*)header + (uintptr_t)stuff[i].inode);
                                             ^~~~~~~~~
                                             intptr_t

Similar changes have been applied earlier in 1e53da3.

This change does not apply to master since e2b4fde added an include of roken.h
to all affected source files which in turn includes stdint.h.

Change-Id: Iddd174e844583e06f66d910052e11feff928ba40
Reviewed-on: https://gerrit.openafs.org/12724
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Anders Kaseorg <andersk@mit.edu>
Tested-by: Anders Kaseorg <andersk@mit.edu>
Reviewed-by: Stephan Wiesand <stephan.wiesand@desy.de>