rxkad: Fix unused-but-set-variable in test/stress.c
clang-19 is flagging a warning/error in rxkad/test/stress.c as
unused-but-set-variables

 stress.c:51:9: error: variable 'nonoauth' set but not used [-Werror,-Wunused-but-set-variable]
    51 |     int nonoauth = 0;
       |         ^
 1 error generated.

The variable nonoauth is initialized and conditionally incremented, but
is not used elsewhere.

Remove the nonoauth variable.

Change-Id: I9a97a3980e5b6ff462f860d7bdae4ee8d7b22971
Reviewed-on: https://gerrit.openafs.org/15984
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>