rx: Add rxi_GetLocalAddr() prototype
Commit 91378d93b9 (rx: Don't send packets to localhost if -rxbind set)
added the rxi_GetLocalAddr() function, but missed the prototype. Add the
function prototype to fix a GCC missing-prototype warning when building
the linux kernel module.

Fixes the build error when building the kernel module for Linux 6.8
or later when the tree was configured with --enable-checking:

  .../src/libafs/MODLOAD-6.8.0-49-generic-SP/rx.c:9693:1: error: no
      previous prototype for ‘rxi_GetLocalAddr’ [-Werror=missing-prototypes]
  9693 | rxi_GetLocalAddr(struct sockaddr_in *sin)
       | ^~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

Reviewed-on: https://gerrit.openafs.org/15978
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Tested-by: Andrew Deason <adeason@sinenomine.net>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Tested-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
(cherry picked from commit d6a2b4b44ddaec54f78737ab1971ffe4d3c28117)

Change-Id: Ief384e4e46b5e46196a88cebd1db6cd30de02f82
Reviewed-on: https://gerrit.openafs.org/16012
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>